### ISSUE TITLE
Update Toil image iRODS connection

### ISSUE THREAD

**Issue by cmball1** [theferrit32/data-commons-workspace#13]
* Modify Toil Docker image `entrypoint.sh` file to set up iROD env variables like Base image.
* Add starting function for Toil image to `/bin/helium`

**Comment by cmball1** [comment]
@stevencox @theferrit32 Updating the Toil Docker image with the same code in `datacommons-base/entrypoint.sh` lines 11-58 into `datacommons-toil/entrypoint.sh` works to define the iRODS environment from env variables. 

However, I am concerned about copying code to multiple places. Especially in the same repository. What do you think of the following:

```
docker/
    common/
        common-entry.sh
    datacommons-base/
        base-entry.sh
        entrypoint.sh
```

Where the new `entrypoint.sh` file will call `common-entry.sh` and `base-entry.sh`. This will give us one place to update common code while allowing a place for specific things like setting up the virtual environment. 

I'm open to other thoughts and ideas, but wanted to provide a starting point.

**Comment by cmball1** [comment]
Another option is to combine the Toil image into the Base image. It seems we will want to build other images such as Jupyter Notebook with both Toil and CWLTool, so this might also be a viable direction.

**Comment by theferrit32** [comment]
Yeah the code duplication was starting to get out of hand, that seems like a good structure.  The code for base-entry.sh could also just be in the entrypoint.sh file, if the entrypoint.sh file will have to be unique per image anyways.  

Combining Toil into the base image with cwltool could be convenient, the only issue there would be the increase in image size, which shouldn't be too bad, but it would be nice to also get the image sizes down a bit if we can.  The base and toil images are around 1GiB, and the jupyter one is up at 1.75.

**Comment by cmball1** [comment]
@theferrit32 I can investigate the image size a bit. What is actually added to the Toil image isn't that big in size, so we should be able to get it down.

It likely has something to do with how Docker builds on the `FROM` image and how everything in that image is included in the new Docker image.

**Comment by cmball1** [comment]
See PR #14 for updates and information.
