### ISSUE TITLE
Propagate exit codes to docker caller

### ISSUE THREAD

**Issue by theferrit32** [theferrit32/data-commons-workspace#28]
Chronos marks all jobs as successful when they stop, even if the workflow command failed because the exit code is thrown away.

**Comment by dcvan24** [comment]
Does the job explicit run, e.g., `exit 1` , on failures? I think Chronos should be able to capture the exit code larger than 0

**Comment by theferrit32** [comment]
the exit code from the entrypoint subcommands are currently discarded so chronos/other will never see the exit code from the workflow step.  I will capture them now and will return them when the container exits.
